server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/chaoxing?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
    driverClassName: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root123}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:seed.sql

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

security:
  token:
    secret: change-me-dev
